services:
  - type: worker
    name: aesthetic-cloud-bot
    env: python
    runtime: python-3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
